menu:
- {name: 'research', url: '/publications'}
- {name: 'cv', url: '/cv'}

social:
- {icon: 'github', link: 'https://github.com/ShaneShang'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/shane-shang-5799a3267'}
