menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}

social:
- {icon: 'github', link: 'https://github.com/ShaneShang'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/shane-shang-5799a3267'}

contacts:
- {name: 'Shane Shang', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
